### ISSUE TITLE
Repository Unusable

### ISSUE THREAD

**Issue by eolszewski** [Airbitz/react-native-secp256k1#1]
Please remove this, it is a false sentinel of hope for those of us trying to get blockchain crypto working in react-native applications.

**Comment by swansontec** [comment]
Ah, good point. Please see https://github.com/Airbitz/react-native-fast-crypto, which has the routines you are looking for. This is what we are using in the Edge app.

**Comment by swansontec** [comment]
I have put a note in the readme file for this repo, directing people to react-native-fast-crypto instead.
